spring.application.name=be-fschool

# Cấu hình kết nối MySQL database (Thay đổi các giá trị bên dưới cho phù hợp với máy của bạn)
spring.datasource.url=jdbc:mysql://localhost:3306/befschool?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Wipy2004@

# Cấu hình Hibernate JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
